name: Spin2cpp CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: install-mingw
      run: "sudo apt-get install gcc-mingw-w64-i686"
    - uses: actions/checkout@v2
    - name: make
      run: make zip
    - name: succ
      run: unzip flexptools.zip -d flexptools-zip
    - run: unzip spin2cpp.zip -d spin2cpp-zip
    - uses: actions/upload-artifact@v2.1.3
      with:
        name: flexptools-git
        path: "flexptools-zip/*"
    - uses: actions/upload-artifact@v2.1.3
      with:
        name: spin2cpp-git
        path: "spin2cpp-zip/*"
  test:
    runs-on: ubuntu-22.04
    steps:
     - uses: actions/checkout@v2
     - name: make
       run: make
     - name: test
       run: make test_offline
  test_spinsim:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
     - uses: actions/checkout@v2
       with:
        submodules: recursive
     - name: make
       run: make
     - name: test
       run: make test_spinsim

